### DISCUSSION TITLE
using external database with EJBCA

### DISCUSSION THREAD

**Discussion by moamen-gamal** [Keyfactor/ejbca-ce#212] [Q&A] [answered]
Greetings,
I'm trying to use ejbca-ce container with an external mariaDB, but when i run the docker compose it shows that the ejbca can't connect to the database, so i would like to know if there is configurations that i did wrong here,
Thanks in advance.

this is my docker-compose file
```
version: '3'
services:
  mariadb:
    image: bitnami/mariadb-galera:latest
    volumes:
      - "mariadb_data:/mariadb"
    networks:
      - localnetwork
    ports:
      - 3306:3306
    container_name: mariadb
    environment:
      - MARIADB_DATABASE=ejbca
      - MARIADB_USER=ejbca
      - MARIADB_PASSWORD=ejbca
      - MARIADB_ROOT_PASSWORD=root
      - ALLOW_EMPTY_PASSWORD=yes
    restart: 'always'

  ejbca:
    image: keyfactor/ejbca-ce:latest
    volumes:
      - ejbca_data:/ejbca/data
    ports:
      - 8443:8443
    networks:
      - localnetwork
    container_name: ejbca-server
    environment:
      - TLS_SETUP_ENABLED=true
      - DATABASE_USER=ejbca
      - DATABASE_PASSWORD=ejbc
      - DATABASE_JDBC_URL=jdbc:mysql://127.0.0.1:3306/ejbca?characterEncoding=UTF-8
    depends_on:
      - mariadb
    links:
      - mariadb
networks:
  localnetwork:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  ejbca_data:
    driver: local

```
and this is the error
`
ejbca-server  | 2023-01-12 09:37:35,280+0000 INFO  [/opt/primekey/bin/start.sh] (process:1) Waiting for external database 'jdbc:mariadb://database:3306/ejbca?characterEncoding=UTF-8' to become available.
ejbca-server  | 2023-01-12 09:37:40,154+0000 INFO  [org.apache.commons.beanutils.FluentPropertyBeanIntrospector] (main) Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
ejbca-server  | 2023-01-12 09:37:50,418+0000 ERROR [org.ejbca.ui.cli.jdbc.JdbcTool] (main) Socket fail to connect to host:address=(host=database)(port=3306)(type=primary). database
ejbca-server  | 2023-01-12 09:37:50,418+0000 INFO  [org.ejbca.ui.cli.jdbc.JdbcTool] (main) Done.
`
