### DISCUSSION TITLE
Custom .properties files in Docker

### DISCUSSION THREAD

**Discussion by sbarnes-tecnica** [Keyfactor/ejbca-ce#288] [Q&A]
Hello,

I'm trying to set up a fresh Docker container, and have been poring over the documentation trying to find the correct way to have the container properly process custom properties (including install.properties)

The only reference I have found is the documentation for a non-container [install](https://doc.primekey.com/ejbca/ejbca-installation/managing-ejbca-configurations), but attempting to supply my own configuration files in the docker-compose file has proven fruitless. Is there something obvious I'm missing here or is this not possible?
My docker-compose.yml that I've been tweaking:
```
version: '3'
networks:
  access-bridge:
    driver: bridge
  application-bridge:
    driver: bridge
services:
  ejbca-database:
    container_name: ejbca-database
    image: "library/mariadb:latest"
    networks:
      - application-bridge
    environment:
      - MYSQL_ROOT_PASSWORD=foo123
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=ejbca
      - MYSQL_PASSWORD=ejbca
    volumes:
      - /opt/docker/mariadb/data:/var/lib/mysql
      - /opt/docker/mariadb/rsyslog:/etc/rsyslog/conf.d
  ejbca:
    hostname: ejbca
    container_name: ejbca
    image: keyfactor/ejbca-ce:latest
    depends_on:
      - ejbca-database
    networks:
      - access-bridge
      - application-bridge
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://ejbca-database:3306/ejbca?characterEncoding=UTF-8
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=true
    volumes:
      - /opt/docker/ejbca/syslog-ng:/etc/syslog-ng/conf.d
      - /opt/docker/ejbca/mysql:/var/lib/mysql
      - /opt/docker/ejbca/data:/var/lib/ejbca
      - /opt/docker/ejbca/data/vault:/opt/keyfactor/ejbca/conf
      - /opt/docker/ejbca/data/conf:/etc/ejbca/conf
    ports:
      - "80:8080"
      - "443:8443"
```

install.properties is under 
`/opt/docker/ejbca/data/vault/install.properties` 
and the other .properties files under 
`/opt/docker/ejbca/conf`
