### DISCUSSION TITLE
EJBCA CE docker compose behind proxy, ManagementCA not created and no adminweb access

### DISCUSSION THREAD

**Discussion by ghost** [Keyfactor/ejbca-ce#302] [Q&A] [answered]
Hello,

I deployed EJBCA CE with docker compose, EJBCA is behind nginx proxy.

I have access to the public interface but not adminweb. 

<details>
  <summary>View screenshot</summary>

- public web
![image](https://github.com/Keyfactor/ejbca-ce/assets/92848369/97303730-3b1d-4a8f-8648-9d478e3735df)

- adminweb

![image](https://github.com/Keyfactor/ejbca-ce/assets/92848369/8ceafab8-7248-4e3b-82c6-800768a04715)
</details>

I know with the default ephemeral setup, it generates the management CA and superadmin.ps12 client cert: https://doc.primekey.com/ejbca/tutorials-and-guides/quick-install-guide

**But how to do it when using custom configuration like this one below ?**

Here's my config:

<details>
  <summary>docker-compose.yml</summary>
  
  ```
version: "3.9"
services:
  ejbca-database:
    container_name: ejbca-database
    image: mariadb:latest
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin --log-bin
    volumes:
      - "./db:/var/lib/mysql:rw"
    #apply user as owner on volume, otherwise systemd-coredump has ownership
    user: "1000:1000"
    environment:
      - MYSQL_ROOT_PASSWORD=ejbca
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=ejbca
      - MSQL_PASSWORD=ejbca
    networks:
      - db-bridge

  ejbca:
    hostname: ejbca-docker
    container_name: ejbca-docker
    image: keyfactor/ejbca-ce:latest
    restart: always
    depends_on:
      - ejbca-database
    environment:
      - DATABASE_JBDC_URL=jbdc:mariadb://ejbca-database:3306/ejbca?characterEncoding=UTF-8
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=false
      - PROXY_HTTP_BIND=0.0.0.0
      - PASSWORD_ENCRYPTION_KEY=strong_password
      - CA_KEYSTOREPASS=strong_password
      - EJBCA_CLI_DEFAULTPASSWORD=strong_password
      - EJBCA_CLI_DEFAULT_USERNAME=ejbca_cli
      - EJBCA_CLI_DEFAULT_PASSWORD=strong_password
      - METRICS_ENABLED=true
    networks:
      - proxy-bridge
      - db-bridge

  nginx:
    hostname: ejbca-proxy
    container_name: ejbca-proxy
    image: nginx
    depends_on:
      - ejbca
    volumes:
      - ./nginx/conf/ejbca.conf:/etc/nginx/conf.d/ejbca.conf
      - ./nginx/certs:/etc/nginx/certs/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - net
      - proxy-bridge

networks:
  proxy-bridge:
    driver: bridge
  db-bridge:
    driver: bridge
  net:
    external: true
  ```
</details>

<details>
  <summary> ejbca.conf (NGINX site conf)</summary>

```
server {
    listen 80;
    server_name pki.company.lan;
    location / {
        proxy_pass                              http://ejbca:8081/;
        proxy_set_header Host                   $http_host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;

        #return 301 https://$host$request_uri;

  }
}

server {
   listen 443 ssl;
   server_name pki.company.lan;
   ssl_certificate     /etc/nginx/certs/cert.pem;
   ssl_certificate_key /etc/nginx/certs/cert.key;



   location / {
        proxy_pass                              http://ejbca:8082/;
        proxy_set_header Host                   $http_host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;
        proxy_set_header SSL_CLIENT_CERT        $ssl_client_cert;
    }
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
}
```
</details>

I tried to generate the Management CA inside the container but I think I got lost somewhere or missed some commands.

#### Step 1 - Token Creation 

```
docker exec -it ejbca-docker ejbca.sh cryptotoken create --token "Management CA Token" --pin "strongPassword" --autoactivate "FALSE" --type SoftCryptoToken --exportkey "TRUE"
```

####  Step 2 - Key Pair Creation
```
docker exec -it ejbca-docker ejbca.sh cryptotoken generatekey --token "Management CA Token" --alias defaultKey --keyspec 4096
docker exec -it ejbca-docker ejbca.sh cryptotoken generatekey --token "Management CA Token" --alias signKey --keyspec 4096
docker exec -it ejbca-docker ejbca.sh cryptotoken generatekey --token "Management CA Token" --alias testKey --keyspec 2048
```
#### Step 3 - Init CA 
```
docker exec -it ejbca-docker ejbca.sh ca init --caname ManagementCA --dn CN=MyCA --keytype RSA -v 7300 --keyspec 4096 -s SHA256WithRSA --policy null --tokenName "Crypto Management CA" --tokenPass "strongPassword" --tokenType soft 
```

- Here's the logs

[docker-compose-logs.txt](https://github.com/Keyfactor/ejbca-ce/files/11742683/docker-compose-logs.txt)

But after that I did not know how to do the next steps

If someone can help me, I would be grateful ! 

thanks

**Comment by cameronfairbairn** [comment]
Hi, I'm also running the container behind an nginx proxy, and had trouble understanding how to obtain the SuperAdmin.p12 certificate - but managed in the end to obtain it.

I loosely followed this tutorial:

https://www.youtube.com/watch?v=oWC5vsGWXQ4&ab_channel=KeyfactorCommunity

I ended up setting the TLS_SETUP_ENABLED flag to "Simple", then logging in to the CA to set the SuperAdmin account up. In this mode, according to the [documentation](https://hub.docker.com/r/keyfactor/ejbca-ce):

_TLS_SETUP_ENABLED="simple" is not recommended except for ephemeral tests without public network access as it gives access to the Admin UI without authentication. Production installation should use_ 

So I used this method to complete the AdminWeb / RA components of the setup after securing my connection with an IP whitelist, then I reverted to the previous configuration, having obtained the certificate.

I hope that helps

**Reply by ghost** [reply]
I tried to setup same way first, without the nginx proxy. The CA was created and SuperAdmin generated, but then after I changed to the proxy configuration and did docker compose down and up, it erased previous container and I got stuck at the same place.

I tried with docker compose restart instead of docker compose down/up but it dit not take the new configuration

**Comment by primetomas** [comment]
With the default setup without TLE_SETUP_ENABLED="simple" you will get console output telling you the superadmin password so you can enroll for it. 
See this discussion as well for someone who did that. 
https://github.com/Keyfactor/ejbca-ce/discussions/299

**Reply by ghost** [reply]
- If i comment the PROXY_HTTP_BIND=0.0.0.0,  and set TLS_SETUP_ENABLED=true,

The logs output correctly:

```
ejbca-docker    | 2023-06-19 08:39:17,207+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Enabling HTTPS listener on 0.0.0.0:8443 with optional client certificate authentication.
ejbca-docker    | 2023-06-19 08:39:23,735+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Enabling HTTP listener on 0.0.0.0:8080.
ejbca-docker    | 2023-06-19 08:39:26,871+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Enabling HSTS
**********************************************************************************************
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *                                                                                            *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) * A fresh installation was detected and a ManagementCA was created for your initial          *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) * administration of the system.                                                              *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *                                                                                            *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) * Initial SuperAdmin client certificate enrollment URL (adapt port to your mapping):         *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *                                                                                            *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *   URL:      https://ejbca-docker:443/ejbca/ra/enrollwithusername.xhtml?username=superadmin *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *   Password: wKQqR0q7HAghuRkeqIZE3+cV                                                       *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *                                                                                            *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) * Once the P12 is downloaded, use "wKQqR0q7HAghuRkeqIZE3+cV" to import it.                   *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *                                                                                            *
ejbca-docker    | 2023-06-19 08:39:34,026+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) **********************************************************************************************
```

But when I try accessing the UI to enroll, I got bad gateway. 

```
ejbca-proxy     | 2023/06/19 08:40:04 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.108, server: pki.company.lan, request: "GET /ejbca/ra/enrollwithusername.xhtml?username=superadmin HTTP/1.1", upstream: "http://172.29.0.2:8082/ejbca/ra/enrollwithusername.xhtml?username=superadmin", host: "pki.company.lan"
```

![image](https://github.com/Keyfactor/ejbca-ce/assets/92848369/8318a5f7-b649-4f12-9c55-9842b50decd5)

Maybe it is because of the nginx proxy that is still redirecting to port 8081 and 8082, so I changed the port to 8080 and 8443 for the proxy pass but It is now invalid and not refused:

```
ejbca-proxy     | 2023/06/19 08:59:05 [error] 30#30: *1 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 192.168.1.108, server: pki.company.lan, request: "GET /ejbca/ra/enrollwithusername.xhtml?username=superadmin HTTP/1.1", upstream: "http://172.31.0.2:8443/ejbca/ra/enrollwithusername.xhtml?username=superadmin", host: "pki.company.lan"
```

![image](https://github.com/Keyfactor/ejbca-ce/assets/92848369/31a3d566-3bc4-408a-a81d-063726104e60)


- If I comment out  PROXY_HTTP_BIND=0.0.0.0 (with nginx proxy pass to 8081 and 8082) and still with TLS_SETUP_ENABLE=true or false, I got access to the WebUI but the Management CA was not created neither the link to enroll superadmin.

**Reply by primetomas** [reply]
Looks like a http call to an https site.
If you get access to Admin UI without Management CA, you have TLS_SETUP_ENABLE="simple". Otherwise client certificate is required. You must have the nginx proxy aware of client certificate authentication.

**Reply by ghost** [reply]
I am aware of the difference between TLS_SETUP_ENABLE= simple / true / false.
I am not using at any point the value **simple**. Since the beginning, I've tried with the values false or true.
I can not get access to the Admin UI in fact.

The TLS certificate used for the proxy for EJBCA public web access is a self signed certificate generated with openssl.

I want to get up a container ready for production. I want a reverse proxy in front end, that is why I enabled PROXY_HTT_BIND, but with this variable enabled, it does not create the CA nor the SuperAdmin to enroll.

Do you have a similar tutorial like this one: https://www.youtube.com/watch?v=oWC5vsGWXQ4&ab_channel=KeyfactorCommunity
But with the TLS_SETUP_ENABLED=true along with reverse proxy configuration ?

What I understand is:

- with TLS_SETUP_ENABLE=simple, the container is listening directly to request and we do not need to setup a proxy.
- with TLS_SETUP_ENABLE=true, the container is listening to 8080 (http) and 8443 (https)
- If i want ejbca container listen to proxy instead of listening directly, I need to setup PROXY_HTTP_BIND
- If PROXY_HTTP_BIND is enabled, the container is listening to 8081 and 8082


Is PROXY_HTTP_BIND really necessary when using reverse proxy ? Or do I need to use PROXY_AJP_BIND ?

**Reply by ghost** [reply]
I retried setup from scratch and without the proxy to begin with, I can't enroll superadmin now..

```
 A fresh installation was detected and a ManagementCA was created for your initial         *
ejbca           | 2023-06-20 09:12:58,906+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) * administration of the system.                                                             *
ejbca           | 2023-06-20 09:12:58,906+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *                                                                                           *
ejbca           | 2023-06-20 09:12:58,906+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) * Initial SuperAdmin client certificate enrollment URL (adapt port to your mapping):        *
ejbca           | 2023-06-20 09:12:58,906+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *                                                                                           *
ejbca           | 2023-06-20 09:12:58,906+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *   URL:      https://ejbca-node1:443/ejbca/ra/enrollwithusername.xhtml?username=superadmin *
ejbca           | 2023-06-20 09:12:58,906+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *   Password: /6Q6ENVa/6ZF+Et2GdMxV9k9                                                      *
ejbca           | 2023-06-20 09:12:58,906+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *                                                                                           *
ejbca           | 2023-06-20 09:12:58,906+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) * Once the P12 is downloaded, use "/6Q6ENVa/6ZF+Et2GdMxV9k9" to import it.                  *
ejbca           | 2023-06-20 09:12:58,906+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) *                                                                                           *
```

![image](https://github.com/Keyfactor/ejbca-ce/assets/92848369/ade0e175-7311-4cfc-b5ab-cb3df1dd6da9)

```
version: '3.9'

services:

  ejbca-database:
    container_name: ejbca-database
    image: mariadb:latest
    networks:
      - application-bridge
    user: "1001:1001"
    environment:
      - MYSQL_ROOT_PASSWORD=foo123
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=ejbca
      - MYSQL_PASSWORD=ejbca
    volumes:
      - ./data:/var/lib/mysql:rw

  ejbca-node1:
    hostname: ejbca-node1
    container_name: ejbca
    image: keyfactor/ejbca-ce:latest
    depends_on:
      - ejbca-database
    networks:
      - access-bridge
      - application-bridge
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://ejbca-database:3306/ejbca?characterEncoding=UTF-8
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=true
    ports:
      - "80:8080"
      - "443:8443"

networks:
  access-bridge:
    driver: bridge
  application-bridge:
    driver: bridge
```
