### DISCUSSION TITLE
EJBCA 8 & Ansible SignServer Playbook support

### DISCUSSION THREAD

**Discussion by walshg3** [Keyfactor/ejbca-ce#341] [Q&A] [answered]
Hello,

Upon trying to install the EJBCA 8 with the SignServer Ansible playbooks I am running into a plethora of issues. Many are due to changes between version 7.4 and 8. One example would be the deprication of EJBCA Public Web effecting the Enrollment protocol variables within the [ansible-ejbca-signserver-playbooks](https://github.com/Keyfactor/ansible-ejbca-signserver-playbooks/tree/31033b1aaefd78a8f9da6a9b90bd134418a50975)/[ansible_ejbca_signsrv](https://github.com/Keyfactor/ansible-ejbca-signserver-playbooks/tree/31033b1aaefd78a8f9da6a9b90bd134418a50975/ansible_ejbca_signsrv)/[group_vars](https://github.com/Keyfactor/ansible-ejbca-signserver-playbooks/tree/31033b1aaefd78a8f9da6a9b90bd134418a50975/ansible_ejbca_signsrv/group_vars)
/ceServers.yml

```YAML
# Enrollment protocols to enable on EJBCA
enable_ejbca_protocols:
  - name: Certstore
  - name: CMP
  - name: CRLstore
  - name: OCSP
  - name: 'Public Web'  -> This breaks playbooks when installing with EJBCA Version 8 
  - name: SCEP
  - name: Webdist
  - name: 'Web Service'
```

The latest release is from over a year ago. That being said I don't mind creating a pull request to fix some issues but my main question is Keyfactor / Primekey still supporting these playbooks or has the overall approach moved to docker / containerization? 

Thank you for working on / supporting such an amazing product.
