### DISCUSSION TITLE
Roadmap for Easy REST Client  (Erce)

### DISCUSSION THREAD

**Discussion by mike-agrenius-kushner** [Keyfactor/ejbca-ce#50] [Q&A]
The [Easy REST Client for EJBCA](https://github.com/Keyfactor/ejbca-easy-rest-client) in its first version only supports

- Enrolling with keys 
- Enrolling and having the client generate keys
- Revocation

What other features would you like to see? Comment below with your suggestions. 

Cheers,
Mike

**Comment by Realiserad** [comment]
Not a feature per se, but I would love to have it delivered as a container image, making it a perfect companion to the EJBCA container image! It would make it way easier to consume for people who are unfamiliar with Java's toolchain.

Maybe consider using GitHub's own container registry over at ``ghcr.io`` and add a GitHub Action to build and publish a new image there whenever someone merges a pull request?

For example:
```yml
name: publish
on:
  push:
    branches:
      - 'main'
jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code from GitHub
      uses: actions/checkout@v2
    - name: Build the container image
      run: docker build -t ghcr.io/keyfactor/erce .
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push the container to GitHub's container registry
      run: docker push ghcr.io/keyfactor/erce
```
