### DISCUSSION TITLE
Howto migrating to docker

### DISCUSSION THREAD

**Discussion by JanKgh** [Keyfactor/ejbca-ce#61] [Q&A]
Hi all,

are there any howtos about  migrating a existing installation with many CA's to a docker installation?
Connecting a external mariadb with a restored ejbca database is easy, but how to store the .properties?
How to connect a persistent volume to the right place?

thx
/jk

**Comment by primetomas** [comment]
There are some examples how to mount properties overrides and such in the GitHub ejbca-containers repo.
https://github.com/Keyfactor/ejbca-containers

**Reply by JanKgh** [reply]
thx tomas for the reply :)

i use docker-compose like this
```
version: '3'

services:
  ejbca:
    container_name: ejbca-app
    image: keyfactor/ejbca-ce:latest
    volumes:
      - ./conf:/etc/ejbca/conf:rw
      - ./conf:/etc/cesecore/conf:rw
    environment:
      - DATABASE_JDBC_URL=jdbc:mysql://10.10.1.20:3306/ejbca?characterEncoding=UTF-8
      - DATABASE_USER=ejbca
      - DATABASE_PASSWORD=****************
      - HTTPSERVER_HOSTNAME=carosi.delta.local
    ports:
      - 8080:8080
      - 8443:8443
```


I imported the db from old ejbca instance and put all .properties from old /opt/ejbca/conf in ./conf,
start the container and all old data are available. But where i have to put the certificate to avoid the generating a new cert?

--
Regards
/jk
