### DISCUSSION TITLE
Starting without plain text db password in docker-compose ENV

### DISCUSSION THREAD

**Discussion by TheNighthawk99** [Keyfactor/ejbca-ce#853] [Q&A] [answered]
Hello,
I am trying to install EJBCA as docker container and I have already followed the YouTube tutorial on how to start a production-like system. It is very detailed but nothing is documented on the matter below.
In terms of security, how we can avoid to pass very unsecured plain text database passwords through the EJBCA docker env as in the video?
MariaDB container can be started up using docker secrets, is the same for EJBCA?

I had tried to find something in the documentation, but I did not find anything useful.

thank you.
Regards.

**Comment by primetomas** [comment]
There is some example for this in the EJBCA helm chart repo. https://github.com/Keyfactor/ejbca-community-helm

**Reply by TheNighthawk99** [reply]
Already read that: that's for Kubernetes, where I am not.
I was wondering if there is a way to install EJBCA as standalone container connected to an external database (as suggested many times in your documentation) without exposing plain text password, username and so on.
The default ones are ejbca, which could be overidden via ENV variables when starting the containers, but it is everything than a safe strategy.

**Reply by primetomas** [reply]
You need some sort of vault for that don't you. Or use a different database authentication scheme, such as a managed identity. Yes this makes it more complicated, and the "standard" way to protect secrets are using a Vault, Docker Secrets or some Kubernetes mechanism. 
Docker Secrets do not work for standalone containers according to their documentation. I can check with some others if they have other ideas.

**Reply by TheNighthawk99** [reply]
I used Docker Secrets with following:

```
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ejbca_db010:/var/lib/mysql:rw
    environment:
      MYSQL_USER: ejbca
      MYSQL_DATABASE: ejbca
      MYSQL_PASSWORD_FILE: /run/secrets/mariadb_user_pwd
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_password
    secrets:
      - mariadb_user_pwd
      - root_password
    networks:
      - backend_net
      
  ejbca:
    image: keyfactor/ejbca-ce:latest
    hostname: 172.16.1.223
    depends_on:
      - mariadb
    ports:
      - 8082:80
      - 8443:443
    environment:
      DATABASE_JDBC_URL: jdbc:mariadb://mariadb:3306/ejbca?characterEncoding=UTF-8
      LOG_LEVEL_APP: INFO
      LOG_LEVEL_SERVER: INFO
      TLS_SETUP_ENABLED: "true"
      DATABASE_USER: ejbca
      DATABASE_PASSWORD_FILE: /run/secrets/mariadb_user_pwd
    secrets:
      - mariadb_user_pwd
    networks:
      - backend_net
    deploy:
      restart_policy:
        condition: none
        
secrets:
  mariadb_user_pwd:
    external: true
  root_password:
    external: true

networks:
  backend_net:
    name: mariadb_backend_network
    external: true

volumes:
  ejbca_db010:
    driver: local
```

I cannot understand if the system does not accept the DATABASE_PASSWORD_FILE env or anything else.
If I use DATABASE_PASSWORD with plain text for both containers, the EJBCA container connects to mariadb and begins the installation.
