### DISCUSSION TITLE
Postman SSL Error: Hostname/IP does not match certificate's altnames

### DISCUSSION THREAD

**Discussion by Curtis-Lockley** [Keyfactor/ejbca-ce#888] [Q&A]
**The issue**
In Postman I have added my **ManagementCA.pem** as a CA certificate. I have also added my generated **.p12** client certificate and tried to do the GET request **https://localhost:443/ejbca/ejbca-rest-api/v1/certificate/status**. However it shows the error message **SSL Error: Hostname/IP does not match certificate's altnames**.  Does anyone know how to resolve this issue?

**Additonal Context**
I have worked through the following tutorials as I am new to EJBCA:

- https://docs.keyfactor.com/ejbca/latest/tutorial-start-out-with-ejbca-docker-container
- https://docs.keyfactor.com/ejbca/latest/tutorial-create-your-first-root-ca-using-ejbca
- https://docs.keyfactor.com/ejbca/latest/tutorial-create-a-pki-hierarchy-in-ejbca
- https://docs.keyfactor.com/ejbca/latest/tutorial-issue-tls-server-certificates-with-ejbca
- https://docs.keyfactor.com/ejbca/latest/tutorial-issue-tls-client-certificates-with-ejbca

This is my docker compose file
```
networks:
  access-bridge:
    driver: bridge
  application-bridge:
    driver: bridge
services:
  ejbca-database:
    container_name: ejbca-database
    image: "library/mariadb:latest"
    networks:
      - application-bridge
    environment:
      - MYSQL_ROOT_PASSWORD=foo123
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=ejbca
      - MYSQL_PASSWORD=ejbca
    volumes:
      - ./datadbdir:/var/lib/mysql:rw
  ejbca-node1:
    hostname: ejbca-node1
    container_name: ejbca
    image: keyfactor/ejbca-ce:latest
    depends_on:
      - ejbca-database
    networks:
      - access-bridge
      - application-bridge
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://ejbca-database:3306/ejbca?characterEncoding=UTF-8
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=simple
    ports:
      - "80:8080"
      - "443:8443"
```

I have also made sure all the CA services are active:
![image](https://github.com/user-attachments/assets/67c03016-5022-4371-ac44-d0f0150ff3d2)

I have also ensured that **REST Certificate Management** is enabled in the system configuration
![image](https://github.com/user-attachments/assets/a87c9c36-19f2-4f4a-8137-f3e73d49eaaa)

I have enrolled the end entity  on the RA Web by going:

1. **Enroll > Make New Request**
2. Select **TLS Client Profile** as the type
3. Select **By the CA**
4. set the common name and username as **Test02**
5.  set and confirm the enrollment code
6. **Download PKCS#12**

My ejbca container has the hostname **ejbca-node1**, but I am trying to do the get request using localhost as I am unable to access the container using **ejbca-node1**. I would've accessed the web ui through **https://localhost/ejbca/adminweb**.
