### DISCUSSION TITLE
Can't remove public access from Super Administrator role

### DISCUSSION THREAD

**Discussion by grzleadams** [Keyfactor/ejbca-ce#909] [General]
I deployed CE v9.1.1 via Helm chart (with ingress enabled, only using our default ingress certificate/enterprise CA instead of generating a certificate as described [here](https://docs.keyfactor.com/container/latest/ejbca/deploy-ca-in-kubernetes#id-(9.3.2-7.3.2)DeployCAinKubernetes-CreatesecretsforIngress)) and everything seems to be working fine, except that when I go to remove public access from the Super Administrator role, I get the following error:
```
Cause: Granted access of the current administrator might be affected by this change.
```
I'm not sure why this is happening since we do have a match for CN in the client certificate, and it accepts that SuperAdmin certificate for authentication through our ingress, so the user's authorization really shouldn't change when that's removed:
![Image](https://github.com/user-attachments/assets/550ef5d9-c7bc-4d95-9064-1659f5b4f156)
It feels like I've misconfigured _something_ but I have no idea what that is, so I appreciate any feedback. Let me know if any more information is needed as well.

**Comment by grzleadams** [comment]
Here are the values I used to deploy:
```
---
image:
  tag: 9.1.1
ejbca:
  useEphemeralH2Database: false
  env:
    DATABASE_JDBC_URL: jdbc:postgresql://postgresql.ejbca.svc.cluster.local:5432/postgres
    DATABASE_USER: postgres
  envRaw:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: postgres-password
services:
  directHttp:
    enabled: false
  proxyHttp:
    enabled: true
    type: ClusterIP
    bindIP: 0.0.0.0
    httpPort: 8081
    httpsPort: 8082
ingress:
  enabled: true
  className: <class>
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-secret: ejbca/managementca-secret
  hosts:
    - host: "ejbca.<domain>"
      paths:
        - path: /ejbca
          pathType: Prefix
  tls:
    - hosts:
        - ejbca.<domain>
```
The managementca-secret contains only the EJBCA CA's public certificate.
