### ISSUE TITLE
Postgres database connection issue 

### ISSUE THREAD

**Issue by sj10v2** [Keyfactor/ejbca-ce#248]
Testing out EJBCA  container version  

Getting the following errors connecting to external postgresql database

2023-02-17 23:24:55,107+0000 INFO  [org.apache.commons.beanutils.FluentPropertyBeanIntrospector] (main) Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
2023-02-17 23:24:55,206+0000 ERROR [org.ejbca.ui.cli.jdbc.JdbcTool] (main) Something unusual has occurred to cause the driver to fail. Please report this exception.
2023-02-17 23:24:55,207+0000 INFO  [org.ejbca.ui.cli.jdbc.JdbcTool] (main) Done.
2023-02-17 23:24:55,226+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Waiting for external database 'jdbc:postgresql://192.168.10.30:5444/ejbcadb' to become available.

FYI port is deliberately set to 5444, postgres is running on a  container.  I'm able to connect using a psql cli client.  

Below is my deployment.yaml file

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-deployment
  namespace: pki
  labels:
    app: ejbca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejbca
  template:
    metadata:
      labels:
        app: ejbca
    spec:
      containers:
      - name: ejbca
        image: keyfactor/ejbca-ce
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "4"
            memory: "3Gi"
          requests:
            cpu: 2000m
            memory: "2Gi"
        ports:
        - containerPort: 8081
          name: proxied-http
        - containerPort: 8082
          name: proxied-https
        env:
        - name: PROXY_HTTP_BIND
          value: "0.0.0.0"
        - name: INITIAL_ADMIN
          value: ";PublicAccessAuthenticationToken:TRANSPORT_ANY;"
        - name: DATABASE_JDBC_URL
          value: jdbc:postgresql://192.168.10.30:5444/ejbcadb #"jdbc:mysql://ejbca-database-service:3306/ejbca?characterEncoding=utf8"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: ejbca-database-credentials
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ejbca-database-credentials
              key: password
```

**Comment by primetomas** [comment]
Your value for DATABASE_JDBC_URL looks very very strange. Remove that mysql part.

**Comment by sj10v2** [comment]
Sorry for the confusion, that mysql part was commented out,  I've removed it entirely  from  yaml deployment file, below is the portion with environment variable.  Still running into the same error described above. 

```
spec:
  containers:
  - env:
    - name: PROXY_HTTP_BIND
      value: 0.0.0.0
    - name: INITIAL_ADMIN
      value: ;PublicAccessAuthenticationToken:TRANSPORT_ANY;
    - name: DATABASE_JDBC_URL
      value: jdbc:postgresql://192.168.10.30:5444/ejbcadb
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          key: username
```
