### ISSUE TITLE
Ingress API version is end-of-live

### ISSUE THREAD

**Issue by kathodion** [Keyfactor/ejbca-ce#255]
Hi
Had problems deploying the file https://github.com/Keyfactor/ejbca-containers/blob/master/deployment-examples/kubernetes/microk8s/ejbca-ce-with-ingress-and-mariadb.yaml
to Azure K8 cluster. The problem occurred around the API version v1beta. Tried to migrate the code to v1 stable, but it needs further testing (I am quite new to K8).

### Here is my version

````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ejbca-ingress
  namespace: ejba-pki-01
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/use-regex annotation: "false"
    # Managing the instance with a client TLS certificate will require additional configuration
    #nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional"
    #nginx.ingress.kubernetes.io/auth-tls-secret: "default/ca-secret"
    #nginx.ingress.kubernetes.io/auth-tls-verify-depth: "3"
    #nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    # Hook
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   proxy_set_header SSL_CLIENT_CERT $ssl_client_cert;
    # AJP is available in nginx-ingress-controller:0.18.0 and later
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/session-cookie-name: "route"
    # nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    # nginx.ingress.kubernetes.io/session-cookie-expires: "1800"
    # nginx.ingress.kubernetes.io/session-cookie-max-age: "1800"
    ingressclass.kubernetes.io/is-default-class: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # Ensure that this hostname is resolvable for example in /etc/hosts if you are doing local testing
  - http:
      paths:
      - path: /ejbca
        pathType: Prefix
        backend:
          service:
            name: ejbca-backend-service
            port:
              number: 8082
````
