### ISSUE TITLE
New EJBCA version redirects to inexistent page

### ISSUE THREAD

**Issue by DatPenguin** [Keyfactor/ejbca-ce#327]
Hi,

I have updated my EJBCA images this morning. Until then, I could access the web interface by using the URL `https://myejbcaserver/`, which redirected me to `https://myejbcaserver/ejbca`. That was a deprecated page, but was still useful for testing with a curl request, for example, to check whether the container is accepting connections.

Since the update, I believe this deprecated page has been deleted, but the redirect still gets me from `/` to `/ejbca`, resulting in an error 404.

Maybe the redirect should now lead to `/ejbca/ra`, or maybe it should be removed?

Thanks.

**Comment by primetomas** [comment]
The redirect is a good point, I think we have a dev ticket for it.. 
For checking if EJBCA is up I recommend using healthcheck. https://doc.primekey.com/ejbca/ejbca-operations/ejbca-operations-guide/ca-operations-guide/ejbca-maintenance/monitoring-and-healthcheck

**Comment by primetomas** [comment]
Thanks, look for new redirects in the next release.

**Comment by primetomas** [comment]
Btw, what do you mean by images? I just tried the latest container and it doesn't have the redirect you mention. What is your image? Is it this WildFly redirect configuration you refer to? 
https://doc.primekey.com/ejbca/ejbca-installation/application-servers/wildfly-26#WildFly26-RedirecttoApplicationforUnknownURLs

I.e. you can change it yourself, but the documentation should be updated?

**Comment by DatPenguin** [comment]
I was talking about this image: https://hub.docker.com/r/keyfactor/ejbca-ce . For context purposes, I am using it with the following `docker-compose.yml` file:
```
version: "3"
networks:
  access-bridge:
    driver: bridge
  application-bridge:
    driver: bridge
services:
  ejbca-node1:
    hostname: pki.mydomain
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        syslog-address: udp://mysyslogserver:514
        syslog-format: rfc5424
        tag: pki
    container_name: ejbca
    image: keyfactor/ejbca-ce:latest
    networks:
      - access-bridge
      - application-bridge
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://mydb:3306/pki?characterEncoding=UTF-8
      - DATABASE_USER=mydbuser
      - DATABASE_PASSWORD=mydpassword
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=simple
    ports:
      - 80:8080
      - 443:8443
```
I just tried it again in private browsing to make sure no cache was acting on it, and when I try to access to https://pki, I do get redirected to https://pki/ejbca/. As you can see in my `docker-compose.yml` file, I do not use any kind of reverse proxy that could change the behavior so if you say there is on redirect in the image I do not really understand what could be going on.
