### ISSUE TITLE
Cannot connect to PostgreSQL or MySQL

### ISSUE THREAD

**Issue by RavilN** [Keyfactor/ejbca-ce#440]
Using Docker image.
Tried to configuire to connect to the database at PostgreSQL. It idid create the database, but tables were not created. Using scripts created tables and indexes, but cannot connect, keeps logging messages:
2023-12-09 11:40:00,229+0000 ERROR [org.ejbca.ui.cli.jdbc.JdbcTool] (main) No suitable driver found for "jdbc:postgresql://postgresql:5432/ejbcadb?characterEncoding=UTF-8"
JDBC drivers seem installed though.
PostgreSQL settings tried also to modify to use MD5 for login as instaructed.
It would be more convenient if tables were created automatically as it happens with h2. And error message does nto look correct based on that drivers are available.

**Comment by primetomas** [comment]
It will create tables if it can connect to the database. The error you post makes it look like it can not connect to the database at all doesn't it?
Without looking into the code myself, wow about just using the url from the documentation, characterEncoding looks like a MySQL setting.
jdbc:postgresql://postgresql:5432/ejbcadb

**Comment by RavilN** [comment]
Tried to remove character encoding part, the same result. 
Using the same credentials can connect from other tool (DBVisualizer) no problem. Has access rights to create dabases and delete.

Here is log fragment:
```

2023-12-11 22:55:08,632+0000 ERROR [org.ejbca.ui.cli.jdbc.JdbcTool] (main) No suitable driver found for "jdbc:postgresql://postgresql:5432/ejbcadb"


2023-12-11 22:55:08,633+0000 INFO  [org.ejbca.ui.cli.jdbc.JdbcTool] (main) Done.


2023-12-11 22:55:08,654+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Waiting for external database '"jdbc:postgresql://postgresql:5432/ejbcadb"' to become available.


2023-12-11 22:55:13,109+0000 INFO  [org.apache.commons.beanutils.FluentPropertyBeanIntrospector] (main) Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.


2023-12-11 22:55:13,227+0000 ERROR [org.ejbca.ui.cli.jdbc.JdbcTool] (main) No suitable driver found for "jdbc:postgresql://postgresql:5432/ejbcadb"


2023-12-11 22:55:13,228+0000 INFO  [org.ejbca.ui.cli.jdbc.JdbcTool] (main) Done.


2023-12-11 22:55:13,249+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Waiting for external database '"jdbc:postgresql://postgresql:5432/ejbcadb"' to become available.


      ```

**Comment by RavilN** [comment]
Here are settings from docker-compose.yml file:

```
  postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=ejbca
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - 'ejbca-psql-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - ejbca

  ejbca.opcua.ca:
    # image: keyfactor/ejbca-ce
    image: primekey/ejbca-ce
    environment:
      - TLS_SETUP_ENABLED="simple"
      - DATABASE_JDBC_URL="jdbc:postgresql://postgresql:5432/ejbcadb"
      - DATABASE_USER="ejbca"
      - DATABASE_PASSWORD="password"
    ports:
      - '9080:8080'
      - '9443:8443'
    networks:
      - ejbca
    volumes:
      - ejbca-mnt-persistent:/mnt/persistent
      - ejbca-mnt-external:/mnt/external
      - ejbca-opt-keyfactor:/opt/keyfactor
  ```

**Comment by primetomas** [comment]
I just tried it locally with postgresql installed and a simple docker command. THe only thing I see is that you use primekey/ejbca-ce instead of keyfactor/ejbca-ce. primekey is deprecated, but should be the same thing right now.

I tested with a simple command like this:

docker pull keyfactor/ejbca-ce

docker run -it --rm -p 80:8080 -p 443:8443 -h localhost -e TLS_SETUP_ENABLED="simple" -e DATABASE_JDBC_URL="jdbc:postgresql://172.26.0.1/ejbcadb" -e DATABASE_USER="ejbca" -e DATABASE_PASSWORD="ejbca" keyfactor/ejbca-ce

and it worked fine. Connection to the database works fine and tables are created automatically in the database when EJBCA is started.
I did get the same error as you (No suitable driver found) when I had a typo in the database connection string, but with that fixed it worked just fine.

**Comment by RavilN** [comment]
Finally made it working. Environment variable values should be without quotes. After removing quotes it could connect to the database. Note: the database is not created automatically, it must be existing. Tables and indexes were created automatically.

Below is example of docker compose file.

```
version: '3'
services:
  ejbca:
    image: keyfactor/ejbca-ce
    hostname: ejbca
    environment:
      - TLS_SETUP_ENABLED=simple
      - DATABASE_JDBC_URL=jdbc:postgresql://postgresql/ejbcadb
      - DATABASE_USER=ejbca
      - DATABASE_PASSWORD=ejbca
      
    ports:
      - '80:8080'
      - '443:8443'
    networks:
      - ejbca
    volumes:
      - ejbca-mnt-persistent:/mnt/persistent
      - ejbca-mnt-external:/mnt/external
      - ejbca-opt-keyfactor:/opt/keyfactor
      
networks:
  ejbca: {}

volumes:
  ejbca-mnt-persistent: {}
  ejbca-mnt-external: {}
  ejbca-opt-keyfactor: {}
  ```
