### ISSUE TITLE
Issues with SCEP

### ISSUE THREAD

**Issue by 0xab3d** [Keyfactor/ejbca-ce#779]
Hello, SCEP issuing is failing on EJBCA CE, created a Wireshark capture and can see the following response. We are self hosting EJBCA-CE.

> **java.lang.ClassCastException: class org.bouncycastle.asn1.DLSequence cannot be cast to class org.bouncycastle.asn1.ASN1OctetString (org.bouncycastle.asn1.DLSequence and org.bouncycastle.as**

![Image](https://github.com/user-attachments/assets/b152b8e8-b8bd-48f6-874a-579322556a32)

**Comment by Realiserad** [comment]
Maybe not related at all, but when you installed EJBCA, did you [remove the version of Bouncy Castle bundled with WildFly)[https://docs.keyfactor.com/ejbca/latest/wildfly-32#id-(9.1.1)WildFly32-RemoveRESTEasy-Crypto]?

**Comment by 0xab3d** [comment]
Hello, I am running it as a docker. Here is the docker compose file content:

```
networks:
  access-bridge:
    driver: bridge
  application-bridge:
    driver: bridge
services:
  ejbca-database:
    container_name: ejbca-database
    image: "library/mariadb:latest"
    networks:
      - application-bridge
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxx
      - MYSQL_DATABASE=xxxx
      - MYSQL_USER=xxxxxxxx
      - MYSQL_PASSWORD=xxxxxx
    volumes:
      - ./datadbdir:/var/lib/mysql:rw
  ejbca-node1:
    hostname: ejbca.domain.com
    container_name: ejbca
    image: keyfactor/ejbca-ce:latest
    depends_on:
      - ejbca-database
    networks:
      - access-bridge
      - application-bridge
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://ejbca-database:3306/ejbca?characterEncoding=UTF-8
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=simple
      - SMTP_DESTINATION=xxxxx
      - SMTP_DESTINATION_PORT=xxxxx
      - SMTP_USERNAME=xxxxxx
      - SMTP_PASSWORD=rxxxxxx
      - SMTP_FROM=xxxxxxx
      - SMTP_SSL_ENABLED=false
      - SMTP_TLS_ENABLED=true
    ports:
      - "8080:8080"
      - "443:8443"
```
